### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by nKodi** [valkyrienyanko/partner-bot#1]
2018-12-17T14:46:10.000369+00:00 app[bot.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): DiscordAPIError: Unknown Channel

**Comment by valkyrienyanko** [comment]
There is a error in your code that is not being caught. Read this https://stackoverflow.com/questions/40500490/what-is-an-unhandled-promise-rejection

**Comment by nKodi** [comment]
Not finding in db

**Comment by valkyrienyanko** [comment]
This was an issue related to [this other issue](https://github.com/valkyrienyanko/partner-bot/issues/2) sorry for not catching it sooner.
