### ISSUE TITLE
Trash emoji help

### ISSUE THREAD

**Issue by Mee6s** [valkyrienyanko/partner-bot#11]
How does one give the bot a trash emote ID to react with.

I can't seem to find anywhere to put an emoji ID, or if I need to add it in somewhere, what would it be called?
I even added emoteID with my own emoji ID in the config.js under the trash one in the Emoji tab thing and I still got the error and no reaction to said message.

help.

**Comment by valkyrienyanko** [comment]
You can either follow this quick fix solution of steps below or remove the custom emote react code entirely. It's up to you.
1. Pull latest changes from 1031865
2. Create a new guild.
3. Add the bot to that guild.
4. Add a custom emote to that guild. Get the ID of that custom emote.
5. Put that custom emote ID into the bots config.
6. Change the bot guild ID in config to the ID of the guild you created.
Next time you run a command, the bot will react with that custom emote prompting you to delete the message.

You could also make it so the bot reacts with a non custom emote which would get rid of the need for the bot to be in a guild of its own with a unique custom emote. I'll eventually do this later on. Sorry for the inconvenience.

**Comment by Mee6s** [comment]
Now I just get this every time I execute a command. 
(node:29164) UnhandledPromiseRejectionWarning: TypeError [EMOJI_TYPE]: Emoji must be a string or GuildEmoji/ReactionEmoji

here is a picture of the config file.
![help](https://user-images.githubusercontent.com/45724082/78947628-221f4300-7a83-11ea-8cc1-b549d8e949fb.jpg)

**Comment by valkyrienyanko** [comment]
You have a extra comma after delete: 'xxxxxxxxxxxxxxx', delete it.
